[local]
localhost

[mongodb]
mongodb.daiops90.online

[redis]
redis.daiops90.online

[mysql]
mysql.daiops90.online

[rabbitmq]
rabbitmq.daiops90.online

[catalogue]
catalogue.daiops90.online

[user]
user.daiops90.online

[cart]
cart.daiops90.online

[shipping]
shipping.daiops90.online

[payment]
payment.daiops90.online

[frontend]
frontend.daiops90.online

[private-key-demo]
172.31.37.172